#!/bin/bash

for i in 3dsim agents api auth common-native common ui; do
        pushd $i
        rm -f node_modules
        vdir="node_modules.$(node --version)"
        mkdir -p $vdir
        ln -s $vdir node_modules
        npm install
        if [ -d node_modules/spacebox-common ]; then
                npm link spacebox-common
        fi
        if [ -d node_modules/spacebox-common-native ]; then
                npm link spacebox-common-native
        fi
        popd
done
